### ISSUE TITLE
Queries 

### ISSUE THREAD

**Issue by abhigoku10** [Nioolek/PPYOLOE_pytorch#1]
@Nioolek  is this code completely not usable ? where is the issuse in ?

**Comment by miemie2013** [comment]
> @Nioolek is this code completely not usable ? where is the issuse in ?

Hi! You can train COCO2017 from scratch with my codes https://github.com/miemie2013/miemiedetection 

just input these commands:
```
wget https://paddledet.bj.bcebos.com/models/pretrained/CSPResNetb_s_pretrained.pdparams
python tools/convert_weights.py -f exps/ppyoloe/ppyoloe_crn_s_300e_coco.py -c CSPResNetb_s_pretrained.pdparams -oc CSPResNetb_s_pretrained.pth -nc 80 --only_backbone True
CUDA_VISIBLE_DEVICES=0,1,2,3,4,5,6,7
python tools/train.py -f exps/ppyoloe/ppyoloe_crn_s_300e_coco.py -d 8 -b 256 -eb 16 -c CSPResNetb_s_pretrained.pth --fp16
```

Please refer to https://github.com/miemie2013/miemiedetection/blob/main/docs/README_PPYOLO.md for more details.

**Comment by Nioolek** [comment]
Now the mAP can get 42.1% on ppyoloe_s,  1% little than the official version.I think this result gap comes from not adding sybn. And I am now training with sybn, wish it can reproduce the result on COCO.

**Comment by abhigoku10** [comment]
@Nioolek will wait for the updated working code base , @miemie2013  thanks for sharing will go thru the source code

**Comment by Nioolek** [comment]
> @Nioolek will wait for the updated working code base , @miemie2013 thanks for sharing will go thru the source code

The code can reproduce the mAP result on COCO, please use it.
