### ISSUE TITLE
将paddle转pytorch模型出现的错误，多谢

### ISSUE THREAD

**Issue by lixiangMindSpore** [Nioolek/PPYOLOE_pytorch#10]
相关的paddle环境和yolox环境都已经装好
![image](https://user-images.githubusercontent.com/78945582/172534405-dae54426-787c-41ac-9774-1c02e7e6ba4a.png)

**Comment by Nioolek** [comment]
这个是之前的一个笔误，将outs9改成outs即可，或者替换成最新版的backbone.py
