### ISSUE TITLE
转成ONNX，并没有做重参数

### ISSUE THREAD

**Issue by sdreamforchen** [Nioolek/PPYOLOE_pytorch#14]
转成ONNX，并没有做重参数。请问如何配置呢？感谢感谢！

**Comment by Nioolek** [comment]
可惜，ppyoloe暂时还未支持转onnx，欢迎提供相关代码

**Comment by Nioolek** [comment]
可惜，该项目ppyoloe代码还未支持转onnx，欢迎提供相关代码

**Comment by sdreamforchen** [comment]
感谢回复。想问下，如果能实现batchsize一样大，卡比官方少一点，会影响精度吗？另外不知道你试过没有加载预权重训练过没？精度能达到多少呢

**Comment by sdreamforchen** [comment]
> 可惜，该项目ppyoloe代码还未支持转onnx，欢迎提供相关代码

如果你这个月不开发。我套路我同事下个月整一个。哈哈
