### ISSUE TITLE
Is there a bug of RepVggBlock in backbone?

### ISSUE THREAD

**Issue by StickCui** [Nioolek/PPYOLOE_pytorch#4]
https://github.com/Nioolek/PPYOLOE_pytorch/blob/61d784a509aa556c3ea00d2f8017d143cb461597/ppyoloe/models/backbone.py#L92

**Comment by Nioolek** [comment]
Oh,yes.I will fix the bug and push the deploy code in few days

**Comment by Nioolek** [comment]
The bug has been fixed
