### ISSUE TITLE
Is there a misstake in backbone

### ISSUE THREAD

**Issue by StickCui** [Nioolek/PPYOLOE_pytorch#7]
https://github.com/Nioolek/PPYOLOE_pytorch/blob/c154b5c88aa6ff4db402c959fc3bdf2c7822af60/ppyoloe/models/backbone.py#L217

**Comment by Nioolek** [comment]
> https://github.com/Nioolek/PPYOLOE_pytorch/blob/c154b5c88aa6ff4db402c959fc3bdf2c7822af60/ppyoloe/models/backbone.py#L217

Oh, yes. Thank you for finding the mistake!
