### ISSUE TITLE
ModuleNotFoundError: No module named 'yolox'

### ISSUE THREAD

**Issue by Yuri-Su** [Nioolek/PPYOLOE_pytorch#8]
执行
` python tools/demo.py image -f exps/ppyoloe/default/ppyoloe_s.py -c model_data/ppyoloe_s.pth --path assets/dog.jpg --conf 0.15 --tsize 640 --save_result --device gpu`
遇到问题
![image](https://user-images.githubusercontent.com/45455052/171321577-9bb1cafb-82cd-4510-a309-74a59b786a8d.png)

![image](https://user-images.githubusercontent.com/45455052/171321587-de411ee2-07ab-4547-ace5-2f0e799b95f2.png)

**Comment by Nioolek** [comment]
没有配置好环境，请运行
`pip3 install -v -e .`
